### ISSUE TITLE
no final product

### ISSUE THREAD

**Issue by JDuggal760** [Tele-Mon/SemiAutoMatedVideoMaker#3]
hey guys, AMAZING IDEA I was going to make this exact same thing with a couple tweaks to it but you guys did it perfectly. There is one issue I'm running into and that's the final.mp4 its not compiling into something they all just stay separate is there a certain place I'm supposed to go or a certain command to get it? Also if you guys want to put your discords/emails/linkedins below ill add you guys, I have a couple places this could go and some extra ideas you guys could look into, but overall love the concept. Installation was a little tough but you just had to install some extra things and then install them one at a time.

**Comment by JDuggal760** [comment]
I think this issue may be at the end I get an error saying 
[concat @ 0x5571e197c140] unsfae file name *.mp4
file_list.txt: Operation is not permitted

**Comment by 0xModded** [comment]
Hey thanks! ill look into the issue int he morning when i wake up or get to school. In the mean time make a PR (pull reequst) with the ideas! id love to hear them!
~Alexis

**Comment by JDuggal760** [comment]
started with updating the README.md. Ill create a PR for the windows installation as soon as I try it. I’ll look at the code after school but some things that could be done are 
-multi broadcasting
-uploading straight to yt with a set desc
-more options for legnth and type of tiktok(for example if they wanted to do funny/cringed/tiktoks
also does this project require minimum specs?
