### ISSUE TITLE
Please meke this project  in python 

### ISSUE THREAD

**Issue by Root-FTW** [Tele-Mon/SemiAutoMatedVideoMaker#8]

**Comment by 0xModded** [comment]
... Did you read the road map? Im currently working on it. Currently trying to figure out the most efficent way to scrape links and then download them using something like youtubedl but for python.

**Comment by Tele-Mon** [comment]
closing as there is litterally no point to this 👎

**Comment by 0xModded** [comment]
closing as there is no point to this 👎

**Comment by Root-FTW** [comment]
ok... 
sorry, I did not mean to bother you

**Comment by 0xModded** [comment]
its alright no hard feelings broskis! all love from the beaches of florida 👍
